# Generated by Django 3.2.19 on 2024-10-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='category',
            field=models.CharField(choices=[('education', 'Education & Learning'), ('business', 'Business & Entrepreneurship'), ('technology', 'Technology & Innovation'), ('creative', 'Creative Arts & Media'), ('health', 'Health & Wellness'), ('sports', 'Sports & Recreation'), ('finance', 'Finance & Investment'), ('social', 'Social Impact & Community Service'), ('environment', 'Environment & Sustainability')], default='Entrepreneurship', max_length=1000),
        ),
    ]
