# Generated by Django 5.1.7 on 2025-03-29 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treasury_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('token_symbol', models.CharField(default='DAO', max_length=10)),
                ('min_tokens_required', models.DecimalField(decimal_places=4, default=1, max_digits=20)),
                ('membership_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('voting_duration_days', models.PositiveIntegerField(default=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dao_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('proposal_type', models.CharField(choices=[('funding', 'Funding Request'), ('governance', 'Governance Change'), ('membership', 'Membership Vote'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('passed', 'Passed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('dao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='dao.dao')),
            ],
        ),
        migrations.CreateModel(
            name='DAOMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_founder', models.BooleanField(default=False)),
                ('voting_power', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dao.dao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dao_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dao')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('for', 'For'), ('against', 'Against')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='dao.proposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('proposal', 'voter')},
            },
        ),
    ]
