# Generated by Django 5.1.7 on 2025-03-29 19:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dao',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='dao',
            name='membership_fee',
        ),
        migrations.RemoveField(
            model_name='dao',
            name='min_tokens_required',
        ),
        migrations.RemoveField(
            model_name='dao',
            name='token_symbol',
        ),
        migrations.RemoveField(
            model_name='dao',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dao',
            name='voting_duration_days',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='dao',
            name='description',
            field=models.TextField(default='A decentralized community for youth innovators.'),
        ),
        migrations.AlterField(
            model_name='dao',
            name='name',
            field=models.CharField(default='Quepter Youth Hub', max_length=100),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dao_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='dao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dao_proposals', to='dao.dao'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 19, 32, 8, 331372, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('failed', 'Failed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('voting_power', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('dao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dao.dao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dao_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dao')},
            },
        ),
        migrations.DeleteModel(
            name='DAOMember',
        ),
    ]
