# Generated by Django 5.1.7 on 2025-04-03 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0002_remove_dao_logo_remove_dao_membership_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 7, 51, 8, 122389, tzinfo=datetime.timezone.utc)),
        ),
    ]
