# Generated by Django 5.1.7 on 2025-04-03 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0004_alter_proposal_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 8, 54, 18, 699997, tzinfo=datetime.timezone.utc)),
        ),
    ]
