# Generated by Django 4.2.18 on 2025-04-03 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0005_alter_proposal_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 11, 12, 1, 317153, tzinfo=datetime.timezone.utc)),
        ),
    ]
