# Generated by Django 5.1.7 on 2025-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20241021_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation_score',
            field=models.IntegerField(default=1),
        ),
    ]
