# Generated by Django 5.1.7 on 2025-03-27 17:09

from django.db import migrations, models

def add_skills(apps, schema_editor):
    Skill = apps.get_model('dashboard', 'Skill')

    skills = [
        'Python', 'Django', 'JavaScript', 'HTML', 'CSS', 'React', 'Node.js', 'Angular',
        'Vue.js', 'SQL', 'NoSQL', 'MongoDB', 'PostgreSQL', 'MySQL', 'REST API', 'GraphQL',
        'Docker', 'Kubernetes', 'AWS', 'Azure', 'GCP', 'Linux', 'Git', 'CI/CD', 'Machine Learning',
        'Deep Learning', 'NLP', 'Computer Vision', 'TensorFlow', 'PyTorch', 'Keras', 'OpenCV',
        'Flask', 'FastAPI', 'Java', 'Spring Boot', 'Kotlin', 'Android Development', 'iOS Development',
        'Swift', 'Objective-C', 'Flutter', 'React Native', 'C', 'C++', 'C#', '.NET', 'PHP', 'Laravel',
        'WordPress', 'Shopify', 'WooCommerce', 'SEO', 'Content Writing', 'Copywriting', 'Marketing',
        'Social Media', 'Salesforce', 'SAP', 'Business Analysis', 'Project Management', 'Scrum',
        'Agile', 'Jira', 'Trello', 'Figma', 'Sketch', 'Adobe XD', 'Photoshop', 'Illustrator', 'Premiere Pro',
        'After Effects', 'Final Cut Pro', 'Blender', 'AutoCAD', '3D Modelling', 'UX Design', 'UI Design',
        'Testing', 'QA', 'Test Automation', 'Selenium', 'Appium', 'Playwright', 'Cybersecurity',
        'Penetration Testing', 'Ethical Hacking', 'Network Security', 'Firewall Configuration',
        'Cryptography', 'Blockchain', 'Smart Contracts', 'Solidity', 'Ethereum', 'Bitcoin', 'Web3',
        'Data Analysis', 'Pandas', 'NumPy', 'Scikit-learn', 'Matplotlib', 'Seaborn', 'Tableau',
        'Power BI', 'Excel', 'Google Sheets', 'SPSS'
    ]

    for skill in skills:
        Skill.objects.get_or_create(name=skill)

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profile_reputation_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(add_skills),
    ]
