# Generated by Django 5.1.7 on 2025-04-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
