# Generated by Django 5.1.7 on 2025-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='funds',
            field=models.FloatField(default=0, max_length=12),
        ),
    ]
