# Generated by Django 5.1.7 on 2025-03-26 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_club_options_club_balance_and_more'),
        ('project', '0002_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timeline', models.IntegerField(help_text='Timeline in days')),
                ('complexity', models.FloatField(default=0.0)),
                ('backing_qpt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('peer_score', models.FloatField(default=0.0)),
                ('engagement_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='club.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate', models.FloatField(default=0.0)),
                ('market_relevance', models.FloatField(default=0.0)),
                ('completion_time', models.IntegerField(default=0)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='project.proposal')),
            ],
            options={
                'ordering': ['-success_rate'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.IntegerField(unique=True)),
                ('prize_pool', models.DecimalField(decimal_places=2, max_digits=20)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Backing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('backer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.proposal')),
            ],
        ),
    ]
