# Generated by Django 5.1.7 on 2025-03-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_qpt_wallet_balance_clubtransaction'),
        ('project', '0003_proposal_performance_competition_backing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project.proposal'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('in_progress', 'In Progress')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='success_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_proposals', to='club.club'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
