# Generated by Django 5.1.6 on 2025-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
