# Generated by Django 3.2.19 on 2024-10-21 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import investment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=investment.models.gen_uuid, editable=False, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Agribusiness', 'Agribusiness'), ('Technology', 'Technology'), ('Health', 'Health'), ('Education', 'Education')], default='Agribusiness', max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('min_points_required', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='MentorshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=investment.models.gen_uuid, editable=False, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInvestmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=investment.models.gen_uuid, editable=False, unique=True)),
                ('application_text', models.TextField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.investmentopportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
