# Generated by Django 5.1.3 on 2024-11-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentopportunity',
            name='account_age_requirements',
            field=models.CharField(choices=[('2', 'must have been active in the respective club for over 2 months'), ('5', 'must have been active in the respective club for over 5 months'), ('10', 'must have been active in the respective club for over 10 months'), ('15', 'must have been active in the respective club for over 15 months'), ('20', 'must have been active in the respective club for over 20 months')], default='2', max_length=100),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='club_required',
            field=models.CharField(choices=[('education', 'Education & Learning'), ('business', 'Business & Entrepreneurship'), ('technology', 'Technology & Innovation'), ('creative', 'Creative Arts & Media'), ('health', 'Health & Wellness'), ('sports', 'Sports & Recreation'), ('finance', 'Finance & Investment'), ('social', 'Social Impact & Community Service'), ('environment', 'Environment & Sustainability')], default='business', max_length=100),
        ),
        migrations.AddField(
            model_name='investmentopportunity',
            name='invites_required',
            field=models.CharField(choices=[('5', 'must have referred at least 5 members'), ('10', 'must have referred at least 10 members'), ('15', 'must have referred at least 15 members'), ('20', 'must have referred at least 20 members'), ('30', 'must have referred at least 30 members')], default='5', max_length=100),
        ),
        migrations.AlterField(
            model_name='investmentopportunity',
            name='category',
            field=models.CharField(choices=[('education', 'Education & Learning'), ('business', 'Business & Entrepreneurship'), ('technology', 'Technology & Innovation'), ('creative', 'Creative Arts & Media'), ('health', 'Health & Wellness'), ('sports', 'Sports & Recreation'), ('finance', 'Finance & Investment'), ('social', 'Social Impact & Community Service'), ('environment', 'Environment & Sustainability')], default='Agribusiness', max_length=1000),
        ),
    ]
