# Generated by Django 5.1.3 on 2024-11-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investmentopportunity_account_age_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentopportunity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='funding'),
        ),
    ]
