# Generated by Django 5.1.6 on 2025-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20241231_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='joining_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clubcontribution',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20),
        ),
    ]
