# Generated by Django 5.1.7 on 2025-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_joining_amount_alter_clubcontribution_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['-reputation_score']},
        ),
        migrations.AddField(
            model_name='club',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='reputation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='club',
            name='total_qpt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
