# Generated by Django 5.1.7 on 2025-03-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_club_app_id_club_encoded_private_key_club_public_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='encoded_private_key',
            new_name='qpt_private_key',
        ),
    ]
