# Generated by Django 3.2.19 on 2024-12-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='category',
            field=models.CharField(default='education', max_length=100),
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
